### ISSUE TITLE
webpages don't display correct if going non-accelerated through the proxy

### ISSUE THREAD

**Issue by piwi3910** [intagger/paraprox#9]
try www.theregister.co.uk or slashdot.org

When non accelerated proxy must be totally transparent

**Comment by piwi3910** [comment]
127.0.0.1:35178 - - [03/Apr/2016 17:03:29] GET http://www.google.com/ads/measurement/l?ebcid=ALh7CaQdZmJiu1ppj43bK3ahhkgv5f9Vr4XNRVbnKg34LQX6pUsS62SF-RmQFRRLDkS1CjyldAhqu45SqN2WVSVSRN-uu1ioVg
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "paraproxio.py", line 237, in handle_request
    self.log_message('%s %s' % (message.method, message.path))  # TODO: integrate aiohttp logging.
  File "paraproxio.py", line 326, in log_message
    mformat % args))
TypeError: not enough arguments for format string
127.0.0.1:35246 - - [03/Apr/2016 17:03:30] GET http://c.betrad.com/a/4.gif
127.0.0.1:35248 - - [03/Apr/2016 17:03:30] GET http://c.betrad.com/ba.html?d803588
127.0.0.1:35178 - - [03/Apr/2016 17:03:30] GET http://www.google.com/ads/measurement/l?ebcid=ALh7CaQdZmJiu1ppj43bK3ahhkgv5f9Vr4XNRVbnKg34LQX6pUsS62SF-RmQFRRLDkS1CjyldAhqu45SqN2WVSVSRN-uu1ioVg
127.0.0.1:35252 - - [03/Apr/2016 17:03:30] GET http://pagead2.googlesyndication.com/pagead/gen_204?id=sodar&v=5&t=2&bgai=BtCKDoBQBV5mrMcy3WOiYlsANAAAAADgB4AQC&bg=!7u1EEO5lV5NPVsICAAAAE1IAAAACCgAFikbVHbWZASfM3FOFkrEp2qYldCoZbGWsMGpd5KtvUVQx1Cy_P1K6JiTcmc8pV02E61Qsm6TRE6V-nEeYbsl9y7NKianAGhfFf6Mg5fNPx8zBAIJSvNHSzX-802Zlkct5vKvDUMd1oVFxKynNqu3cpDJiRNMtYSVOMNcRLOqhR8uD1BIEDe0phhu_4S65EHpaT2bmVK5VVqByofPpYzl07aFd16Ok8dX6cSmjlfkk47Wv9rCE_qKkw9LY0DBy89vJf4oqqvy13VJpiUwq7MpejV7nFuN2JPe5xJyrSD4-LZlu0BW-IIdYNRDTnXF_CRzTBeVN6y1D6oUPPizG1GPxCJoFLRQEOAG5wH5TvVa5_Ezt5L2GGkvJ7c8GpnG5R0kWQOD1Xa-hB78kBJ6uPUrt
127.0.0.1:35260 - - [03/Apr/2016 17:03:30] GET http://c.betrad.com/a/n/322/4311.js
127.0.0.1:35268 - - [03/Apr/2016 17:03:31] GET http://c.betrad.com/icon/box_19_top-right.png
127.0.0.1:35270 - - [03/Apr/2016 17:03:31] GET http://c.betrad.com/icon/gi.png
127.0.0.1:35272 - - [03/Apr/2016 17:03:31] GET http://l.betrad.com/ct/0_0_0_4311/row/0/1/0/0/0/0/728/90/242/322/0/pixel.gif?v=d803588_1&ttid=2&d=tpc.googlesyndication.com&r=0.6712399620071128
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "paraproxio.py", line 237, in handle_request
    self.log_message('%s %s' % (message.method, message.path))  # TODO: integrate aiohttp logging.
  File "paraproxio.py", line 326, in log_message
    mformat % args))
TypeError: not enough arguments for format string
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "paraproxio.py", line 237, in handle_request
    self.log_message('%s %s' % (message.method, message.path))  # TODO: integrate aiohttp logging.
  File "paraproxio.py", line 326, in log_message
    mformat % args))
TypeError: not enough arguments for format string
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "paraproxio.py", line 237, in handle_request
    self.log_message('%s %s' % (message.method, message.path))  # TODO: integrate aiohttp logging.
  File "paraproxio.py", line 326, in log_message
    mformat % args))
TypeError: not enough arguments for format string
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "paraproxio.py", line 237, in handle_request
    self.log_message('%s %s' % (message.method, message.path))  # TODO: integrate aiohttp logging.
  File "paraproxio.py", line 326, in log_message
    mformat % args))
TypeError: not enough arguments for format string

**Comment by intagger** [comment]
Have you tried to set a proxy manually in firefox like this?
![selection_066](https://cloud.githubusercontent.com/assets/289916/14232759/303845d6-f9bd-11e5-8e19-780c7517ffa3.png)

**Comment by piwi3910** [comment]
![without-proxy](https://cloud.githubusercontent.com/assets/12539757/14245630/abd0e7e6-fa73-11e5-9981-72084fd1f777.png)
![with-proxy](https://cloud.githubusercontent.com/assets/12539757/14245631/abd1e164-fa73-11e5-8b54-c8723daecf36.png)
![proxy-settings](https://cloud.githubusercontent.com/assets/12539757/14245629/abd0b9c4-fa73-11e5-9cb4-948029da0940.png)

**Comment by intagger** [comment]
Very strange, because i don't see any difference with and without proxy on my machine.
In both cases I see the same as on your second screenshot (without ads).

**Comment by piwi3910** [comment]
after you change back without proxy, you need to clear your web cache

**Comment by intagger** [comment]
yes. just get this =)

**Comment by intagger** [comment]
also I had to disable uBlock Origin.

**Comment by intagger** [comment]
I found the bug with a truncated css file http://www.theregister.co.uk/Design/style/design/moz.css?bo

**Comment by intagger** [comment]
Fixed with commit 0efeb015f0b119c5ad731f5e366172f0cd594ff0
